name: CI

on:
    pull_request:
    push:
        branches:
            - master

jobs:
    php-cs-fixer:
        name: php-cs-fixer
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Install dependencies with composer
                uses: php-actions/composer@v6

            -   name: Run PHP-CS-Fixer
                run: vendor/bin/php-cs-fixer fix --dry-run --using-cache=no --config=.php-cs-fixer.dist.php
